---
- hosts: localhost
  gather_facts: False
  tasks:

    # Get the authentication cookie
  - uri:
      url: https://{{ vco.eth0.ansible }}/portal/rest/login/operatorLogin
      method: POST
      body: "{{ lookup('template', 'templates/operator-login.j2') }}"
      body_format: json
      validate_certs: no
      headers:
        Content-Type: "application/json"
        Accept-Type: "application/json"
    register: login
    ignore_errors: no

  # Configure vco
  - uri:
      url: https://{{ vco.eth0.ansible }}/portal/rest/enterprise/insertEnterprise
      method: POST
      body: "{{ lookup('template', 'templates/configure-vco.j2') }}"
      body_format: json
      validate_certs: no
      headers:
        Content-Type: "application/json"
        Accept-Type: "application/json"
        Cookie: "{{login.set_cookie}}"
    register: vco_config
    ignore_errors: yes

  # Get the authentication cookie (AS AN ENTERPRISE ADMIN)
  - uri:
      url: https://{{ vco.eth0.ansible }}/portal/rest/login/enterpriseLogin
      method: POST
      body: "{{ lookup('template', 'templates/enterprise-login.j2') }}"
      body_format: json
      validate_certs: no
      headers:
        Content-Type: "application/json"
        Accept-Type: "application/json"
    register: login
    ignore_errors: no

  # Configure Profile
  - uri:
      url: https://{{ vco.eth0.ansible }}/portal/rest/configuration/cloneEnterpriseTemplate
      method: POST
      body: "{{ lookup('template', 'templates/configure-profile.j2') }}"
      body_format: json
      validate_certs: no
      headers:
        Content-Type: "application/json"
        Accept-Type: "application/json"
        Cookie: "{{login.set_cookie}}"
    register: vco_profile
    ignore_errors: yes

  # Get entreprise Configuration
  - uri:
      url: https://{{ vco.eth0.ansible }}/portal/rest/enterprise/getEnterpriseConfigurations
      method: POST
      body: "{{ lookup('template', 'templates/get-enterpriseconfiguration.j2') }}"
      body_format: json
      validate_certs: no
      headers:
        Content-Type: "application/json"
        Accept-Type: "application/json"
        Cookie: "{{login.set_cookie}}"
    register: getconfiguration

  - debug:
      msg: "{{ item.modules }}"
    with_items: "{{ getconfiguration.json }}"
    when:
        (item.description == "Antoine")

  # Update entreprise Configuration
  - uri:
      url: https://{{ vco.eth0.ansible }}/portal/rest/configuration/updateConfigurationModule
      method: POST
      body: "{{ lookup('template', 'templates/antoine-profile.j2') }}"
      body_format: json
      validate_certs: no
      headers:
        Content-Type: "application/json"
        Accept-Type: "application/json"
        Cookie: "{{login.set_cookie}}"
    register: setconfiguration


